app/func/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/6/22 下午9:51
# @Author  : Bear Chao
# @Site    : http://blog.nickzy.com
# @File    : forms.py
# @Software: PyCharm
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField,BooleanField
from wtforms.validators import DataRequired, Length, NumberRange


class NewTaskForm(FlaskForm):
    dataType = SelectField('任务类型',choices=[('file','本地文件'),('ftp','FTP'),('SMB','SMB文件共享'),('mysql','MySQL')])
    name = StringField('描述')
    dir = StringField('地址\目录')
    port = IntegerField('端口号',validators=[NumberRange(1,65535,'请输入正确的端口号')])
    username = StringField('用户名', validators=[DataRequired(), Length(1, 64), ])
    password = StringField('密码', validators=[DataRequired()])
    target = StringField('目标文件夹\数据库')
    tables = StringField('数据表')
    finger = StringField('finger')
    count = IntegerField('运行次数')
    delete = BooleanField()

app/func/__init__.py
from flask import Blueprint

func = Blueprint('func', __name__)

from . import task_views,job_views,ipconfig_view

app/func/views.py
from flask import render_template, redirect, url_for, request
from flask_login import login_required

from app.func.forms import NewTaskForm
from app.main.views import common_list
from app.models import Task
from control.task.task import get_finger
from . import func

# 主页
@func.route('/home', methods=['GET'])
@login_required
def home():
    return render_template('func/home.html')

#任务列表
@func.route('/task/list', methods=['GET'])
@login_required
def taskList():
    return common_list(Task,'func/tasklist.html')

#删除任务
@func.route('/task/delete/<finger>')
def deleteTask(finger):
    try:
        task = Task.get(Task.finger == finger)
        task.delete_instance()
        return render_template('auth/respond.json',state='success')
    except:
        return render_template('auth/respond.json',state='fail',message='操作失败')


#新建任务
@func.route('/task/new', methods=['POST','GET'])
def newTask():
    form = NewTaskForm()
    if request.method == 'POST':

        if request.form['finger']:
            task = Task.get(finger = request.form['finger'])
        else:
            task = Task()
            task.finger = get_finger()
            task.count = 0
        task.dataType = request.form['dataType']
        task.name = request.form['name']
        task.dir = request.form['dir']
        task.username = request.form['username']
        task.password = request.form['password']
        task.port = request.form['port']
        task.tables = request.form['tables']
        task.target = request.form['target']
        #todo 检测参数是否正确
        task.save()
        return render_template('auth/respond.json',state="success")
    return render_template('fragment/new_task.html', form = form)

#编辑任务
@func.route('/task/edit/<finger>')
def editTask(finger):
    task = Task.get(Task.finger==finger)
    form = NewTaskForm()
    form.finger.data = task.finger
    form.dataType.data = task.dataType
    form.name.data = task.name
    form.dir.data = task.dir
    form.username.data = task.username
    form.password.data = task.password
    form.port.data = task.port
    form.tables.data = task.tables
    form.target.data = task.target
    form.count.data = task.count
    return render_template('fragment/new_task.html', form=form)

app/templates/func/home.html
<div class="content_wrapper">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <aside>
                    <header><i class="fa fa-fw fa-home"></i>工作台</header>
                    <section>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12">
                                    {% if message %}
                                        <div class="alert alert-warning">
                                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                            {{ message }}
                                            <form id="uploadForm" enctype="multipart/form-data">
                                                <input id="file" type="file" name="file"/>
                                                <button id="upload" class="btn btn-info btn-sm" type="button">上传激活文件</button>
                                            </form>
                                        </div>
                                    {% endif %}
                                    <div class="my_panel">
                                        <div class="heading">欢迎信息</div>
                                        <div class="body">您好：{{ current_user.fullname }}！当前系统为<strong>{{ info.stat }}</strong></div>
                                    </div>
                                    <div class="my_panel">
                                        <div class="heading">系统信息</div>
                                        <div class="body">
                                            <table class="table table-striped">
                                                <tbody>
                                                <tr>
                                                    <td width="200">软件版本</td>
                                                    <td>v1.2.1</td>
                                                </tr>
                                                <tr>
                                                    <td>操作系统</td>
                                                    <td>{{ info.platform }}</td>
                                                </tr>
                                                <tr>
                                                    <td>系统架构</td>
                                                    <td>{{ info.machine }}</td>
                                                </tr>
                                                <tr>
                                                    <td>内存占用</td>
                                                    <td>{{ info.memory }}%</td>
                                                </tr>
                                                <tr>
                                                    <td>磁盘占用</td>
                                                    <td>{{ info.disk }}%</td>
                                                </tr>
                                                <tr>
                                                    <td>系统启动时间</td>
                                                    <td>{{ info.boot_time }}</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="my_panel">
                                        <div class="heading">运行状态</div>
                                        <div class="body" style="height: 510px">
                                             <div id="chart1" style="height:500px;width:49%;border:1px solid #ccc;padding:2px;float: left"></div>
                                             <div id="chart2" style="height:500px;width:49%;border:1px solid #ccc;padding:2px;float: right"></div>
                                        </div>
                                    </div>
                                    <div class="my_panel">
                                        <div class="heading">开发团队</div>
                                        <div class="body">
                                            <table class="table table-striped">
                                                <tbody>
                                                <tr>
                                                    <td width="200">创建者</td>
                                                    <td>Bear Chao</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    </div>

</div>
<script>
$("#upload").click(function(){
  $.ajax({
        url: '{{ url_for('main.uploadkey') }}',
        type: 'POST',
        cache: false,
        data: new FormData($('#uploadForm')[0]),
        processData: false,
        contentType: false
    }).done(function(res) {
        alert(res)
    }).fail(function(res) {
        alert(res)
    });
});

var date = [];
var data =[];
var data2 = [];

var myChart = echarts.init(document.getElementById('chart1'));
var chart2 = echarts.init(document.getElementById('chart2'));
// 基于准备好的dom，初始化echarts实例

var now = new Date();
date.push(now.toLocaleTimeString());
data.push(0);
data2.push(0);

// 指定图表的配置项和数据
var option = {
    title: {
        text: 'CPU占用'
    },
    tooltip: {},

    xAxis: {
        data: date
    },
    yAxis: {},
    series: [{
        name: 'cpu',
        type: 'line',
        data: data
    }]
};
var option2 = {
    title: {
        text: '内存占用'
    },
    tooltip: {},

    xAxis: {
        data: date
    },
    yAxis: {},
    series: [{
        name: '模拟数据',
        type: 'line',
        data: data2
    }]
};

 // 使用刚指定的配置项和数据显示图表。
  myChart.setOption(option);
  chart2.setOption(option2);

    // 异步更新数据 （以后，定时post，取回1个数据）
    var timeTicket = setInterval(function () {
        $.post('/info').done(function (d) {
            time = new Date();
            date.push(time.toLocaleTimeString());
            if (data.length > 100){
                date.shift();
                data.shift();
                data2.shift();
            }
            data.push(d.cpu);
            data2.push(d.mem);
            myChart.setOption({
                xAxis:{
                    data:date
                },
                series:[{
                data: data
                }]
            });
            chart2.setOption({
                xAxis:{
                    data:date
                },
                series:[{
                data: data2
                }]
            });
        });
    }, 3000);
</script>

app/templates/func/job_detail.html
<div class="content_wrapper">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <aside>
                    <header><i class="fa fa-fw fa-list-ul"></i>job列表</header>
                    <section>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="btn-group" style="margin-bottom:20px;">
                                        <button class="btn btn-default" onclick="loadURL('{{ url_for('func.task_jobs') }}')"><i class="fa fa-backward"></i>返回</button>
                                    </div>
                                <div class="col-sm-12">
                                    <div class="table-responsive">
                                       {% if jobs %}
                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th>任务代码</th>
                                                <th>执行周期</th>
                                                <th>上次运行时间</th>
                                                <th>状态</th>
                                                <th>有效性</th>
                                                <th>操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            {% for row in jobs %}
                                            <tr>
                                                <td>{{ row.comment }}</td>
                                                <td>{{ row.minute }}</td>
                                                <td>{{ row.last_run }}</td>
                                                <td>{{ row.is_enabled() }}</td>
                                                <td>{{ row.is_valid() }}</td>
                                                <td>
{#   todo:修改job                                                 <button class="btn btn-default btn-xs J_ajax_content_modal" data-href="{{ url_for('func.edit_job_page',finger = row.comment, index = loop.index) }}">修改</button>#}
                                                    <button class="btn btn-info btn-xs J_ajax_content_modal" data-href="{{ url_for('func.newJob',finger = row.comment) }}">启用</button>
                                                    <button type="button" class="btn btn-warning btn-xs J_confirm_modal " data-tip="将要删除该任务的全部job，是否操作？" data-target="{{ url_for('func.delete_job',finger = row.comment,index = loop.index) }}">删除</button>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    </div>

</div>

app/templates/func/taskJobs.html
<div class="content_wrapper">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <aside>
                    <header><i class="fa fa-fw fa-calendar-check-o"></i>自动化管理</header>
                    <section>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="table-responsive">
                                       {% if form %}
                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th width="60">任务代码</th>
                                                <th width="80">任务类型</th>
                                                <th>描述</th>
                                                <th >job数量</th>
                                                <th width="80">运行次数</th>
                                                <th >操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            {% for row in form.content %}
                                            <tr>
                                                <td>{{ row.finger }}</td>
                                                <td>{{ row.dataType }}</td>
                                                <td>{{ row.name }}</td>
                                                <td>
{#                                                一个小hack，解决jinja变量作用域问题，实现计数#}
                                                {% set num = [] %}
                                                {% for job in arg %}
                                                    {% set comment = job.comment|int %}
                                                    {% if comment == row.finger %}
                                                       {% if num.append(0) %}{% endif %}
                                                    {% endif %}
                                                {% endfor %}
                                                {% if num|length == 0 %}
                                                    <span class="label label-default">{{ num|length }}</span>
                                                {% else %}
                                                    <span class="label label-info">{{ num|length }}</span>
                                                    <button type="button" class="btn btn-link" onclick="loadURL('{{ url_for('func.jobDetail',finger = row.finger) }}')">查看job详情</button>
                                                {% endif %}
                                                </td>
                                                <td><label class="badge">{{ row.count }}</label></td>
                                                <td>
                                                    <button class="btn btn-info btn-xs J_ajax_content_modal" data-href="{{ url_for('func.newJob',finger = row.finger) }}">创建job</button>
                                                    <button type="button" class="btn btn-warning btn-xs J_confirm_modal " data-tip="将要删除该任务的全部job，是否操作？" data-target="{{ url_for('func.deleteTask',finger = row.finger) }}">删除所有job</button>
                                                    <button class="btn btn-success btn-xs J_ajax_content_modal" data-href="{{ url_for('func.run',finger = row.finger) }}">立即执行</button>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    {% endif %}
                                    </div>
                                    <nav>
                                        {% if form %}
                                        <ul class="pagination">
                                            <li class="disabled"><a href="#">共{{ form.total_count }}条</a></li>
                                            {% if form.page <= 1 %}
                                                <li class="disabled"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                            {% else %}
                                                <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.task_jobs') }}?page={{form.page - 1}}')"><i class="fa fa-angle-left"></i></a></li>
                                            {% endif %}
                                            {% for i in range(1, form.total_page + 1) %}
                                                {% if i == form.page %}
                                                    <li class="active"><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.task_jobs') }}?page={{i}}')">{{ i }}</a></li>
                                                {% endif %}
                                                {% if i!=form.page %}
                                                    <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.task_jobs') }}?page={{i}}')"> {{ i }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if form.page == form.total_count %}
                                                 <li class="disabled"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                            {% else %}
                                            <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.taskList') }}?page={{form.page + 1}}')"><i class="fa fa-angle-right"></i></a></li>
                                            {% endif %}
                                        {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    </div>

</div>

app/templates/func/tasklist.html
<div class="content_wrapper">

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <aside>
                    <header><i class="fa fa-fw fa-list-ul"></i>任务列表</header>
                    <section>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="btn-group" style="margin-bottom:20px;">
{#                                        <button class="btn btn-default J_ajax_content_modal" data-href="/fragment/query"><i class="fa fa-filter"></i>查询</button>#}
                                        <button class="btn btn-default J_ajax_content_modal" data-href="{{ url_for('func.newTask') }}"><i class="fa fa-file"></i>新建任务</button>
                                    </div>
                                    <div class="table-responsive">
                                       {% if form %}
                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th width="50">运行次数</th>
                                                <th width="60">任务代码</th>
                                                <th width="80">任务类型</th>
                                                <th>描述</th>
                                                <th>地址\目录</th>
                                                <th width="70">目标</th>
                                                <th width="60">帐号</th>
                                                <th width="60">密码</th>
                                                <th width="95">操作</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for row in form.content %}
                                            <tr>
                                                <td><label class="badge">{{ row.count }}</label></td>
                                                <td>{{ row.finger }}</td>
                                                <td>{{ row.dataType }}</td>
                                                <td>{{ row.name }}</td>
                                                <td>{{ row.dir }}</td>
                                                <td>{{ row.target }}</td>
                                                <td>{{ row.username }}</td>
                                                <td>{{ row.password }}</td>
                                                <td>
                                                    <button class="btn btn-primary btn-xs J_ajax_content_modal" data-href="{{ url_for('func.editTask',finger = row.finger) }}">编辑</button>
                                                    <button type="button" class="btn btn-warning btn-xs J_confirm_modal " data-tip="一定要删除？" data-target="{{ url_for('func.deleteTask',finger = row.finger) }}">删除</button>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    {% endif %}
                                    </div>
                                    <nav>
                                        {% if form %}
                                        <ul class="pagination">
                                            <li class="disabled"><a href="#">共{{ form.total_count }}条</a></li>
                                            {% if form.page <= 1 %}
                                                <li class="disabled"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                                            {% else %}
                                                <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.taskList') }}?page={{form.page - 1}}')"><i class="fa fa-angle-left"></i></a></li>
                                            {% endif %}
                                            {% for i in range(1, form.total_page + 1) %}
                                                {% if i == form.page %}
                                                    <li class="active"><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.taskList') }}?page={{i}}')">{{ i }}</a></li>
                                                {% endif %}
                                                {% if i!=form.page %}
                                                    <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.taskList') }}?page={{i}}')"> {{ i }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if form.page == form.total_count %}
                                                 <li class="disabled"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                            {% else %}
                                            <li><a href="javascript:void(0);" onclick="loadURL('{{ url_for('func.taskList') }}?page={{form.page + 1}}')"><i class="fa fa-angle-right"></i></a></li>
                                            {% endif %}
                                        {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </section>
                </aside>
            </div>
        </div>
    </div>

</div>